<?xml version="1.0"?>

<!--  https://github.com/ros/urdf_tutorial/blob/master/urdf/08-macroed.urdf.xacro -->

<robot name="macroed" xmlns:xacro="http://ros.org/wiki/xacro">


    <xacro:property name="width" value="0.2" />
    <xacro:property name="leglen" value="0.6" />
    <xacro:property name="polelen" value="0.2" />
    <xacro:property name="bodylen" value="0.6" />
    <xacro:property name="baselen" value="0.4" />
    <xacro:property name="wheeldiam" value="0.07" />
    <xacro:property name="pi" value="3.1415" />

    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>


    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>


    <xacro:macro name="wheel" params="prefix suffix reflect">
        <link name="${prefix}_${suffix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                    <geometry>
                        <cylinder radius="${wheeldiam/2}" length="0.1"/>
                    </geometry>
                <material name="black"/>
            </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                    <geometry>
                        <cylinder radius="${wheeldiam/2}" length="0.1"/>
                    </geometry>
                </collision>
            <xacro:default_inertial mass="1"/>
        </link>
        <joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
            <axis xyz="0 1 0" rpy="0 0 0" />
                <parent link="${prefix}_base"/>
                <child link="${prefix}_${suffix}_wheel"/>
            <origin xyz="${baselen*reflect/3} 0 -${wheeldiam/2+.05}" rpy="0 0 0"/>
        </joint>

    </xacro:macro>








    <xacro:macro name="leg" params="prefix reflect">
        <link name="${prefix}_leg">
            <visual>
                <geometry>
                    <box size="${leglen} 0.1 0.2"/>
                </geometry>
                <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${leglen} 0.1 0.2"/>
                </geometry>
            <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
            </collision>
        <xacro:default_inertial mass="10"/>
        </link>

        <joint name="base_to_${prefix}_leg" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_leg"/>
            <origin xyz="0 ${reflect*(width+.02)} 0.25" />
        </joint>

        <link name="${prefix}_base">
            <visual>
                <geometry>
                    <box size="${baselen} 0.1 0.1"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${baselen} 0.1 0.1"/>
                </geometry>
            </collision>
            <xacro:default_inertial mass="10"/>
        </link>

        <joint name="${prefix}_base_joint" type="fixed">
            <parent link="${prefix}_leg"/>
            <child link="${prefix}_base"/>
            <origin xyz="0 0 ${-leglen}" />
        </joint>
        <xacro:wheel prefix="${prefix}" suffix="front" reflect="1"/>
        <xacro:wheel prefix="${prefix}" suffix="back" reflect="-1"/>
    </xacro:macro>


    <xacro:leg prefix="right" reflect="-1" />
    <xacro:leg prefix="left" reflect="1" />


    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${width}" length="${bodylen}"/>
            </geometry>
        <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${width}" length="${bodylen}"/>
            </geometry>
        </collision>
    <xacro:default_inertial mass="10"/>
    </link>




</robot>